### ISSUE TITLE
Tabla de Pago y Cuotas

### ISSUE THREAD

**Issue by siberiaaa** [G3-Graco/laboratorio-nice-team#6]
Será necesario guardar toda esa información (fecha y pago) en tabla de pago? Ya que como la tabla cuota está enlazada a pago, y cuota ya tiene esos datos sería información redundante.

Igualmente se planteaba que, es necesaria la tabla de pago en sí? Ya que la única información relevante adicional que nos da, es desde qué cuenta se efectúa el pago, sin embargo no me parece "correcto" no tener una tabla pago y que se guarde ese dato en la cuota. Así que creo que es mejor tener la tabla pago porque estructuralmente es más lógico así. 

Entonces se me ocurrió que a lo mejor se deja como una sencilla tabla intermedia pago, que lo único que tendrá será la foreign key de a qué cuota corresponde el pago y la foreign key de desde qué cuenta se efectúa el pago. 
Eso ó eliminar completamente la tabla pago y guardar la cuenta de donde se efectuó el pago en la tabla cuota.

![image](https://github.com/G3-Graco/laboratorio-nice-team/assets/128342488/71f12e98-58d9-452c-a339-3a7be260ba94)

**Comment by GGimenezG** [comment]
Bien está perfecto esa forma de pensar, si bien la cuota puede tener la información del monto que se paga y la fecha del pago, puedes ver la tabla pago cómo la tabla como una recibo o comprobante, tendra un id único la cuenta asociada y la cuota asociada.

Deben tener en cuenta que la cuota es de un préstamo, si asociamos la cuota a pago puede faltar la información del préstamo al que está relacionado

Queda más o menos revuelto siendo una tabla Intermedia

**Comment by siberiaaa** [comment]
Por qué si se asocia la cuota al pago podría faltar información del préstamo? Ya que de necesitar información del préstamo, la misma cuota tiene guardada la foreign key de a qué préstamo está relacionado y por ende acceder a esa información? 

O sea entendí que mejor dejo la tabla pago como una tabla intermedia sin mayor información, lo único que me quedó en duda fue lo que le escribí arriba
